[details]
name = "Loom"
description = "Native Wally package manager for Roblox Studio."

[versions]
"0.0.1" = {ref = "https://github.com/J4KEWasNotHere/Loom/releases/download/v0.0.1/LoomPlugin.rbxm"}
